#!/usr/bin/env bash

test -d $1 && echo "USAGE: build <name>" && exit 1

echo creating basic structure
mkdir -p $1/{bin,src,test}

echo creating build script
echo "#!/usr/bin/env bash

gcc -g src/$1.c -o bin/$1" > $1/build && chmod +x $1/build

echo creating suite script
echo "#!/usr/bin/env bash

PATH=$PATH:$(pwd)/$1/bin
cd test 
./unit && echo passed. || echo failed." > $1/suite && chmod +x $1/suite

echo creating unit stub
echo "#!/usr/bin/env bash

echo should pass
exit 1" > $1/test/unit && chmod +x $1/test/unit

echo creating program stub
echo "#include <stdio.h>

int main() {
}" > $1/src/$1.c
