#!/usr/bin/env bash

# usage

function usage {
  echo generates a tcpl project.
  echo
  echo usage:
  echo
  echo generate -n name \\
  echo \  [-s stub_file]
  echo
  echo defaults:
  echo
  echo \  stub_file: $stub_file
  echo
}

stub_file="stub"

while getopts "n:s:h" option
do
  case "$option" in
    n)
      name="$OPTARG"
      ;;
    s)
      stub_file="$OPTARG"
      ;;
    h)
      usage
      exit 0
      ;;
    [?])
      usage
      exit 1
      ;;
  esac
done

if [[ -z $name ]] || [[ -z $stub_file ]]
  then
    usage
    exit 1
fi

auto=$name/auto
build=$name/Makefile
helpers=$name/test/helpers
src=$name/src/$name.c
suite=$name/suite
unit=$name/test/unit

# directories

echo creating basic structure
mkdir -p $name/{bin,src,test}

# build script

echo creating build script
cp config/Makefile $build

# suite script

echo creating suite script
cp config/suite $suite
sed -i '' "s/\${name}/$name/g" $suite

# auto

echo creating auto script
cp config/auto $auto

# once

if ! test -f $helpers
  then
    echo creating helpers script
    cp config/helpers $helpers
    sed -i '' "s/\${name}/$name/g" $helpers
fi

if ! test -f $unit
  then
    echo creating unit stub
    cp config/unit $unit
    sed -i '' "s/\${name}/$name/g" $unit
fi

if ! test -f $src
  then
    echo creating program stub
    cp config/$stub_file.c $src
fi

