#!/usr/bin/env bash

# usage

if ! test $1
  then
    echo "USAGE: generate <name>."
    exit 1
fi

name=$(basename $1)

auto=$name/auto
build=$name/build
helpers=$name/test/helpers
src=$name/src/$name.c
suite=$name/suite
unit=$name/test/unit

# directories

echo creating basic structure
mkdir -p $name/{bin,src,test}

# build script

echo creating build script
cp config/build $build
sed -i '' "s/\${name}/$name/g" $build

# suite script

echo creating suite script
cp config/suite $suite
sed -i '' "s/\${name}/$name/g" $suite

# auto

echo creating auto script
cp config/auto $auto

# once

if ! test -f $helpers
  then
    echo creating helpers script
    cp config/helpers $helpers
fi

if ! test -f $unit
  then
    echo creating unit stub
    cp config/unit $unit
    sed -i '' "s/\${name}/$name/g" $unit
fi

if ! test -f $src
  then
    echo creating program stub
    cp config/stub.c $src
fi

