#!/usr/bin/env bash

spacestab() {
  local col="$1"

  ruby -e "($col - 1).times { print ' ' }; print \"\t\""
}

assert_detabs_to() {
  local expansion="$1"
  local column="$2"
  local expected=$(( $column + $expansion - 1 ))

  spacestab "$column" | 1.20 | wc -c | xargs test "$expected" =
}

