#!/usr/bin/env bash

echo Should check a C program for rudimentary syntax errors, by...
echo

echo detecting unmached opening parenthesis:
echo "(" | 1.24 | grep "unclosed ( at end of file" || exit 1

echo detecting unmached closing parenthesis:
echo ")" | 1.24 | grep "contains unbalanced ) at 1:1" || exit 1

echo validating matching parenthesis:
echo "()" | 1.24 || exit 1

echo detecting unmached opening brackets:
echo "[" | 1.24 | grep "unclosed \[ at end of file" || exit 1

echo detecting unmached closing brackets:
echo "]" | 1.24 | grep "contains unbalanced \] at 1:1" || exit 1

echo detecting unmached opening braces:
echo "{" | 1.24 | grep "unclosed { at end of file" || exit 1

echo detecting unmached closing braces:
echo "}" | 1.24 | grep "contains unbalanced } at 1:1" || exit 1

echo detecting unmached single quotes:
echo "'" | 1.24 | grep "unclosed ' at end of file" || exit 1

echo detecting unmached double quotes:
echo "\"" | 1.24 | grep "unclosed \" at end of file" || exit 1

echo validating matching single quotes:
echo "''" | 1.24 || exit 1

echo validating matching double quotes:
echo "\"\"" | 1.24 || exit 1

echo validating char double quote
echo "'\"'" | 1.24 || exit 1

echo validating escaped char single quote
echo "'\''" | 1.24 || exit 1

echo validating escpaped string double quote
echo "\"\\\"\"" | 1.24 || exit 1

echo ignoring stacked tokens inside a comment
echo "/* ignore this { */" | 1.24 || exit 1

echo ignoring stacked tokens inside a cpp style omment
echo "// ignore this { " | 1.24 || exit 1

echo ignoring stacked tokens inside a string
echo "\"{\"" | 1.24 || exit 1

echo ignoring stacked tokens inside a single quoted char
echo "'{'" | 1.24 || exit 1

echo correctly revalidating a source file already validated by a compiler
cat ../src/1.24.c | 1.24 || exit 1
