#!/usr/bin/env bash

assert_calculates() {
  local expected="$1"
  local expression="$2"

  echo "$expression" | 4.06 | grep "^${expected}$" || {
    echo error: $(echo "$expression" | 4.06), not $expected
    false
  }
}

