#!/usr/bin/env bash

echo Should output the correct ranges for integral types, specifically:
echo

echo unsigned char range should be foo
2.01 | grep char | grep foo || exit 1

echo unsigned short range should be foo
2.01 | grep char | grep foo || exit 1

echo unsigned int range should be foo
2.01 | grep char | grep foo || exit 1

echo unsigned long range should be foo
2.01 | grep char | grep foo || exit 1

echo signed char range should be foo
2.01 | grep char | grep foo || exit 1

echo signed short range should be foo
2.01 | grep char | grep foo || exit 1

echo signed int range should be foo
2.01 | grep char | grep foo || exit 1

echo signed long range should be foo
2.01 | grep char | grep foo || exit 1

echo PENDING: Should output the correct ranges for floating point types, specifically:
echo

false || exit 1
