#!/usr/bin/env bash

echo "should convert tabs to \t"
echo "tab: 	" | 1.10 | grep "\t" || exit 1

echo "should convert backslashes to \\"
echo "backslash: \\" | 1.10 | grep "\\\\" || exit 1

echo "should convert backspaces to \b"
echo "backspace: " | 1.10 | grep "\b" || exit 1
