#!/usr/bin/env bash

assert_debtabs() {
  local input="$1"
  local expected="$(printf $2)"

  printf "$input" | 1.21 | grep "$expected" || {
    echo input: "$input"
    echo output: $(printf "$input" | 1.21)
    false
  }
}

