#!/usr/bin/env bash

assert_calculates() {
  local expected="$1"
  local expression="$2"

  echo "$expression" | 4.03 | grep "^${expected}$" || {
    echo  error: $(echo "$expression" | 4.03), not $expected
    false
  }
}

