#!/usr/bin/env bash

assert_strips() {
  local input="$1"
  local expected="$2"

  echo "$input" | 1.23 | grep "$expected" || {
    echo error for input "$input": $(echo "$input" | 1.23)
    false
  }
}

